name: Echo-test

on:
  push:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vimtor/action-zip@v1.1
      with:
        files: dist/ manifest.json
        recursive: false
        dest: result.zip
    - run: |
          date > generated.txt
          git config user.name H-but-fancy
          git config user.email echodot69420@gmail.com
          git add .
          git commit -m "generated"
          git push
