name: Echo-test

on:
  push:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/upload-artifact@v1.1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/result.zip
