name: zip

on:
  push:
    branches:
      - main

jobs:
  zip:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: zip -r CIPack.zip assets/ pack.mcmeta pack.png
    - run: sha1sum CIpack.zip > CIpack.zip.sha1sum

    - uses: pyTooling/Actions/releaser@main
      with:
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: CIpack.zip*
